[package]
name = "regexp-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
grex = "1.4.5"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
